### ISSUE TITLE
with square instead of circle?

### ISSUE THREAD

**Issue by hyperrjas** [marcaube/bootstrap-magnify#8]
with square instead of circle?

**Comment by marcaube** [comment]
Overwrite the `border-radius` on `.magnify-large`

``` css
.magnify-large {
    -webkit-border-radius: 0;
       -moz-border-radius: 0;
            border-radius: 0;
}
```
